---
- name: Configure Web Application
  hosts: all
  become: yes
  tasks:
    - name: Copy HTML file to Nginx location
      copy:
        src: "/webapp/webapp/deploy_app_ansible/index.html"
        dest: /usr/share/nginx/html/index.html 
      notify: Reload Nginx
    
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded
